name = "sarvatech"
main = ".output/server/index.mjs"
pages_build_output_dir = "./dist"
compatibility_date = "2025-02-12"

[assets]
binding = "ASSETS"
directory = ".output/public/"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "nuxt-content"
database_id = "968681e6-9ec1-48ef-861b-014f4a45865a"
