name = "sarvatech"
pages_build_output_dir = "./dist"
compatibility_date = "2025-02-12"

[[d1_databases]]
binding = "DB"
database_name = "nuxt-content"
database_id = "968681e6-9ec1-48ef-861b-014f4a45865a"
